### ISSUE TITLE
IPv6 Address Truncated on Single Visitor Insights under Session Details

### ISSUE THREAD

**Issue by kipmyk** [wp-statistics/wp-statistics#850]
### Issue Summary:

When viewing a visitor with an IPv6 address in the Single Visitor section, the IP address is displayed incompletely. The full IPv6 address is cut off or partially hidden.

### Steps to Reproduce:
1. Go to the WordPress admin dashboard.
2. Navigate to Statistics → Single Visitor.
3. Click View on any visitor with an IPv6 address.
4. Observe that the displayed IP address is incomplete or truncated.

As shown: 

<img width="1476" alt="Image" src="https://github.com/user-attachments/assets/2161fbd1-36b1-41cd-a005-e8c8eda86562" />

### Expected Behavior:
The entire IPv6 address should be shown clearly without any parts being cut off, regardless of length.

### Environment:

WP Statistics Version 14.13.4

Browser: Chrome

Operating System: macOS 

### Possible workaround

```css
.wps-visitor__visitors-detail--row div span {
    word-break: break-word;
    overflow-wrap: anywhere;
    white-space: normal;
    display: inline-block;
    max-width: 100%;
}
```
