### ISSUE TITLE
Overflow-X Issue on WP Statistics Overview Page (Traffic Summary)

### ISSUE THREAD

**Issue by kipmyk** [wp-statistics/wp-statistics#852]
### Summary

The WP Statistics plugin (version 14.13.4) exhibits a horizontal overflow (overflow-x) issue on the Overview page, specifically within the Traffic Summary widget. 

### Steps to Reproduce

1. Install and activate WP Statistics (v14.13.4) on a WordPress site.
2. Navigate to the WordPress admin dashboard.
3. Go to WP Statistics > Overview (`/wp-admin/admin.php?page=wps_overview_page`).
4. Observe the Traffic Summary widget (`#wp-statistics-traffic-summary-widget`).
5. Resize the browser window to various widths (e.g., 1440px, 1024px, 768px, 375px) or inspect on different devices.
6. Check for horizontal scrollbars or clipped content within the Traffic Summary widget, particularly in the table (.o-table-wrapper) containing visitor and view statistics.

### Expected Behavior

- The Traffic Summary widget should remain fully contained within its parent container (#side-sortables) without triggering horizontal scrollbars.
- Table content (.o-table) should adapt to the available width, either by wrapping text, truncating with ellipsis, or using responsive table techniques (e.g., horizontal scrolling within the table container only).
- The widget should maintain a clean, responsive layout across all screen sizes, consistent with WordPress admin design standards.

### Proposed Fix

The following CSS can mitigate the issue by constraining the table and its contents to the parent container’s width, with responsive adjustments:

```css
#side-sortables {
    overflow-x: hidden;
    width: 100%;
    box-sizing: border-box;
}

.o-table-wrapper {
    overflow-x: auto;
    width: 100%;
    max-width: 100%;
}

.o-table {
    width: 100%;
    max-width: 100%;
    table-layout: auto;
    border-collapse: collapse;
}

.o-table td {
    word-wrap: break-word;
    word-break: break-word;
    max-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
}

@media screen and (max-width: 782px) {
    .o-table td {
        font-size: 14px;
        padding: 8px;
    }
}
```
